/**
 * @file main.c
 * @brief Example program to measure a voltage on an ESP32 Analog to Digital
 * channel and write it to a SSD106 OLED display over an I2c serial connection.
 *
 * @author Jim Sutton
 * @date August 24 2020
 *
 * Copyright 2020 Jim Sutton
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

#include "esp_err.h"
#include "esp_log.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "driver/gpio.h"
#include "driver/adc.h"
#include "driver/dac.h"
#include "driver/i2c.h"
#include "esp_system.h"
#include "sdkconfig.h" // generated by "make menuconfig"

#include "my_print1.h"
#include "oled_ssd1306.h"
#include "font8x8_basic.h"

#define SDA_PIN GPIO_NUM_21 // serial data line old value 18
#define SCL_PIN GPIO_NUM_22 // serial clock line old value 19
#define DAC_EXAMPLE_CHANNEL     CONFIG_EXAMPLE_DAC_CHANNEL
#define ADC1_EXAMPLE_CHANNEL    CONFIG_EXAMPLE_ADC1_CHANNEL

#define tag "SSD1306"

void i2c_master_init() {
// This configures an i2c driver. Reference i2c driver API from Espressif
// ESP32 supports 2 i2c connections, this will be number 0.

	i2c_config_t i2c_config = {
		.mode = I2C_MODE_MASTER,
		.sda_io_num = SDA_PIN,
		.scl_io_num = SCL_PIN,
		.sda_pullup_en = GPIO_PULLUP_ENABLE,
		.scl_pullup_en = GPIO_PULLUP_ENABLE,
		.master.clk_speed = 1000000
	};
	i2c_param_config(I2C_NUM_0, &i2c_config);
	i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
}

void ssd1306_init() {
	// initialiaze the OLED 1306 display chip
	esp_err_t espRc; // for error reporting

	i2c_cmd_handle_t cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	// send a single byte with the i2c bus address and an embedded write request
	// set by the LSB = 0 to initiate a transaction with the slave
	// true indicates you want acknowledgement
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	// after requesting connection send 1 byte to specify if data or commands
	// will be transmitted
	i2c_master_write_byte(cmd, OLED_CONTROL_SET_WRITE_CMD, true);

	// Configure Memory addressing mode as Page mode
	// See Table 9 Solomon Systech Technical Data sheet
	i2c_master_write_byte(cmd, OLED_CMD_SET_MEMORY_ADDR_MODE, true); //request to choose addr mode
	i2c_master_write_byte(cmd, OLED_CMD_SET_PAGE_ADDR_MODE, true); // set page addr mode
	i2c_master_write_byte(cmd, OLED_CMD_SET_PAGEM_START_COL_L, true); // set lower nibble of col start addr
	i2c_master_write_byte(cmd, OLED_CMD_SET_PAGEM_START_COL_H, true); // set lower nibble of col start addr
	i2c_master_write_byte(cmd, OLED_CMD_SET_PAGEM_START_PAGE, true); // set start page in GDDRAM

	i2c_master_write_byte(cmd, OLED_CMD_SET_CHARGE_PUMP, true);
	i2c_master_write_byte(cmd, 0x14, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_SEGMENT_REMAP, true); // reverse left-right mapping
	i2c_master_write_byte(cmd, OLED_CMD_SET_COM_SCAN_MODE, true); // reverse up-bottom mapping

	i2c_master_write_byte(cmd, OLED_CMD_DISPLAY_ON, true);
	i2c_master_stop(cmd);

	// now send the commands to the SSD1306. Report result in espRc
	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "OLED configured successfully");
	} else {
		ESP_LOGE(tag, "OLED configuration failed. code: 0x%.2X", espRc);
	}
	i2c_cmd_link_delete(cmd);
}

void oled_display_clear() {

	i2c_cmd_handle_t cmd;

	// create array of blanks to load onto device to clear the memory
	uint8_t zero[128];
	memset(&zero,0,128);

	// loop through the 8 pages (each page has 8 rows)
	for (uint8_t i = 0; i < 8; i++) {
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_SET_WRITE_CMD, true); // use command mode
		i2c_master_write_byte(cmd, 0xB0 | i, true); // to set the pointer to the row to clear. 0xB0 clears row 0
		i2c_master_stop(cmd);

		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);

		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_SET_WRITE_DATA, true); // use data XFER mode to load GDDRAM
		i2c_master_write(cmd, zero, 128, true); // load row (page) with 128 blank columns
		i2c_master_stop(cmd);

		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);
	}
}

void oled_display_scroll() {
	/* This function sets up the OLED display so that
		 Row 0 is static
		 Row 1 Scrolls Horrizontally
		 Row 2 Scrolls Horrizontally
		 Row 3 Scrolls Horrizontally
		 Rows 4-7 Scroll Horrizontally and Vertically
	*/
	esp_err_t espRc;

	i2c_cmd_handle_t cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);

	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, OLED_CONTROL_SET_WRITE_CMD, true);

	// Setup vertical and Horrizontal scroll function for rows 1 to 7
	// 0x29 is a right scroll
	i2c_master_write_byte(cmd, 0x29, true); // vertical and horizontal scroll (p29)
	i2c_master_write_byte(cmd, 0x00, true); // dummy byte
	i2c_master_write_byte(cmd, 0x01, true); // define PAGE1 as start page
	i2c_master_write_byte(cmd, 0x06, true); // set time interval between each
	                                        // scroll step as 2 frames
	i2c_master_write_byte(cmd, 0x07, true); // define PAGE7 as end page
	i2c_master_write_byte(cmd, 0x01, true); // set vertical scrolling offset as
		                                      // scroll step as 1 row

	// Setup vertical scroll area with command 0xA3 for rows 4 to 7
	// rows that are in the vertical and horrizontal scroll area AND in The
	// vertical scroll area will scroll both Horrizontally and Vertically. Else Rows
	// will only go horrizontally. In this case the vertical area is the lower
	// 4 rows.
	i2c_master_write_byte(cmd, 0xA3, true); // set vertical scroll area (p30)
	i2c_master_write_byte(cmd, 0x20, true); // set the number of rows in top non-vertical area
	i2c_master_write_byte(cmd, 0x20, true); // set the nuber of rows in vertical scrolling area

	i2c_master_write_byte(cmd, 0x2F, true); // activate scroll (p29)

	i2c_master_stop(cmd);
	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "Scroll command succeeded");
	} else {
		ESP_LOGE(tag, "Scroll command failed. code: 0x%.2X", espRc);
	}

	i2c_cmd_link_delete(cmd);
}

void oled_display_text(const char *text) {

	i2c_cmd_handle_t cmd;
	uint8_t cur_page = 0, i=0, cur_line_char_written=0;

	cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, OLED_CONTROL_SET_WRITE_CMD, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_PAGEM_START_COL_L, true); // set column low nibble to 0
	i2c_master_write_byte(cmd, OLED_CMD_SET_PAGEM_START_COL_H, true); // set column high nibble to 0
	i2c_master_write_byte(cmd, 0xB0 | cur_page, true); // set row to page0

	i2c_master_stop(cmd);
	i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	i2c_cmd_link_delete(cmd);

	for (i = 0; i < strlen(text); i++) {
		if (text[i] == '\n') {
			cur_line_char_written=0;
			cmd = i2c_cmd_link_create();
			i2c_master_start(cmd);
			i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
			i2c_master_write_byte(cmd, OLED_CONTROL_SET_WRITE_CMD, true);

			i2c_master_write_byte(cmd, OLED_CMD_SET_PAGEM_START_COL_L, true); // set column low nibble to 0
			i2c_master_write_byte(cmd, OLED_CMD_SET_PAGEM_START_COL_H, true); // set column high nibble to 0
			i2c_master_write_byte(cmd, 0xB0 | ++cur_page, true); // increment page

			i2c_master_stop(cmd);
			i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
			i2c_cmd_link_delete(cmd);
		} else {
			if(cur_line_char_written < 16) { // Max chars per line is 16 (for 128x64 pixels, 8px*16chars=128px)
				cmd = i2c_cmd_link_create();
				i2c_master_start(cmd);
				i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
				i2c_master_write_byte(cmd, OLED_CONTROL_SET_WRITE_DATA, true);

				i2c_master_write(cmd, font8x8_basic_tr[(uint8_t)text[i]], 8, true);

				i2c_master_stop(cmd);
				i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
				i2c_cmd_link_delete(cmd);
				cur_line_char_written++;
			}
		}
	}
}
void init_ADC(){
  ESP_LOGI(tag, "Initialize Analag to Digital Converter 1");

  esp_err_t r;
  gpio_num_t adc_gpio_num;

  r = adc1_pad_get_io_num( ADC1_EXAMPLE_CHANNEL, &adc_gpio_num );
  assert( r == ESP_OK );
  ESP_LOGI(tag, "ADC1 channel %d @ GPIO %d \n", ADC1_EXAMPLE_CHANNEL, adc_gpio_num);


  adc1_config_width(ADC_WIDTH_BIT_12);
  adc1_config_channel_atten( ADC1_EXAMPLE_CHANNEL, ADC_ATTEN_DB_11 ); //0 to 3.9VDC
}

void init_DAC(){

  ESP_LOGI(tag, "Initialize Digital to Analog Converter");

  esp_err_t r;
  gpio_num_t dac_gpio_num;

  r = dac_pad_get_io_num( DAC_EXAMPLE_CHANNEL, &dac_gpio_num );
  assert( r == ESP_OK );

  ESP_LOGI(tag, "DAC channel %d @ GPIO %d.\n", DAC_EXAMPLE_CHANNEL + 1, dac_gpio_num );
  dac_output_enable( DAC_EXAMPLE_CHANNEL );
}

float dac_set_voltage(int dac_set_point){
    float dac_output_vdc; //DAC output volts DC (0-3.3 VDC)
    dac_output_vdc = dac_set_point * 0.01289063;
    return dac_output_vdc;
}

float adc_measured_voltage1(int adc_measured_counts){
    float adc_input_vdc;
    adc_input_vdc = adc_measured_counts * 0.000952; // 3.9 divided by 4096
    return adc_input_vdc;
}

int span_pct_integer(int adc_measured_counts){
  int span_percent;
  span_percent = (int) (adc_measured_voltage1(adc_measured_counts)*30.3);
	span_percent = (float) span_percent * -2.703 + 191.89 + .5;
  if (span_percent < 0){
    span_percent = 0;
  }
  else {if (span_percent > 100){
    span_percent = 100;
    }
  }

  return span_percent;
}

void span_pct_string(int adc_measured_counts, char* span){
    sprintf(span,"%3d", span_pct_integer(adc_measured_counts));
    return;
}

void app_main(void) {
	uint8_t dac_set_point=0;
	int adc_measured_counts=0;

	char span[4] = "";
	char oled_message [32] ="";

	init_ADC();
	init_DAC();

	vTaskDelay(2 * portTICK_PERIOD_MS);

	ESP_LOGI(tag, "start conversion.\n");
	//printf("  DAC Count    DAC VDC  ADC Count    ADC VDC   Span PCT"
	//"   Digit[0]   Digit[1]   Digit[2]\n");

	i2c_master_init();
	ssd1306_init();
	oled_display_clear();

	//char str[] = "  Stone Tablet  \n\nOLED Working\n\n\n\n\n\nX";
	char str[] = "\n\n\n\n\n\n\n\nX";
	oled_display_text(str);
	//oled_display_scroll();

	while(1) {
		// test external components
		 	myPrintf1( 2 );

			dac_output_voltage( DAC_EXAMPLE_CHANNEL, dac_set_point );
			adc_measured_counts = adc1_get_raw( ADC1_EXAMPLE_CHANNEL);

			span_pct_string(adc_measured_counts,span);
			/*
			printf("%11d %10.2f %10d %10.2f %10d %10c %10c %10c\n",
			dac_set_point, // 0 to 256 is the input range of the DAC
			dac_set_voltage(dac_set_point), //Calculated output voltage from the DAC
			adc_measured_counts, // input counts measured by ADC range is 0 to 4096
			adc_measured_voltage1(adc_measured_counts), //Calculated ADC voltage
			span_pct_integer(adc_measured_counts), //Span (0-100) recorded by ADC integer
			span[0], span[1], span[2]); //Span (0-100) recorded by ADC as string
			*/

			dac_set_point++;

			strcpy(oled_message, "  Stone Tablet  \n\nMoisture ");
			strcat(oled_message,span);
			strcat(oled_message," %");

			oled_display_text(oled_message);

			vTaskDelay( 2 * portTICK_PERIOD_MS );
	}
}
